Document: emptty
Title: Debian emptty Manual
Author: <insert document author here>
Abstract: This manual describes what emptty is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/emptty/emptty.sgml.gz

Format: postscript
Files: /usr/share/doc/emptty/emptty.ps.gz

Format: text
Files: /usr/share/doc/emptty/emptty.text.gz

Format: HTML
Index: /usr/share/doc/emptty/html/index.html
Files: /usr/share/doc/emptty/html/*.html
